server:
  port: 18889

logging:
  path: logs
  file: log.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testNg?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: cxk
    password:

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
